import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import Link from 'next/link'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="h-10 bg-slate-200 p-4 flex items-center gap-x-2 shadow-sm">
          {
            ['dashboard', 'blog'].map((item) => {
              return <Link className="p-2" key={item} href={`/${item}`}>{item}</Link>
            })
          }
        </header>
        <main className="p-4">
          {children}
        </main>
        <footer className="bg-slate-200 p-4 flex justify-center">
          app footer
        </footer>
      </body>
    </html>
  )
}
